
#pragma config(Sensor, S4,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          arm1,          tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorC,          arm2,          tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorD,          pen,           tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ttt_armcontrol.c"
//--------------------------------------------------------------------
//											||DECLARATIONS|| ROBOT NAME = gmb
//--------------------------------------------------------------------
//

bool foundOppPlay = false;
bool playedTurn = false;
bool restartGame = true;
bool matCheck[3][3];
int emptyBox = 0;
int foe = 5;
int robot = 7;
void updateOpponentPlay();
//void playBallAt(int x, int y);
void updateMatCheck();
void resetMatCheck();
void nextPlay();
//void resetMatCheck();
int getVert(int col);
int getHorz(int row);
int getDiag(int oneTwo);
void playBallAt(int x, int y);
void vertPlay(int col);
void horzPlay(int row);
void diagPlay(int oneTwo);
void playGame();
bool gmbPlaysFirst();
bool gmbFirst = false;
int foePlayCount = 0;
void displayBoard();
void extraWinCheck();


//GLOBAL VARIABLES
/*************************************************************
**************X'S AND O'S ARE STORED HERE*********************
**************************************************************/
char char_mat[3][3];
int atX = 0;
int atY = 0;
int fwd =  100000000;
int bkwd = -100000000;
int mat[3][3];

void displayBoard(){
drawLine(50, 10, 50, 120);
drawLine(100, 10, 100, 120);
drawLine(10, 50, 150, 50);
drawLine(10, 90, 150, 90);

for(int i=0; i<3; i++){
		for(int j=0; j<3;j++){
			if(mat[i][j]== 5){
				drawEllipse(i*50+10, j*50, 25+(i*50)+10, 25+(j*50));
			}else if (mat[i][j]== 7){
				drawLine(i*50+10, j*55, (i*50)+40, 25+(j*50)+10);
				drawLine(i*50+40, j*55, (i*50)+10, 25+(j*50)+10);
				//drawRect(i*50+10, j*50, 25+(i*50)+10, 25+(j*50));
      sleep(100);
			}
		}
	}
}
	//////////////////////////////////////////////////////
	////////***********MAIN FUNCTION***********///////////
	//////////////////////////////////////////////////////
task main()
{

		//SETUP:
	//LINE UP INSIDE SUPPORT WITH 0,2 AND FINAL WITH 3,1.5
	//////////////////////////////////////////////////////
	resetMotorEncoder(arm1);
	resetMotorEncoder(arm2);
	//sets the starting point where the arm is
	goHome();
	startTask (moveArm1);
	startTask (moveArm2);

	playGame();

	while (true){
		if (restartGame == true){
			//wait 5 seconds to restart game
		sleep(5000);
		playGame();
		}
	}

}

void playGame(){
	restartGame = false;
	//initialize array to zeros
	for(int i=0; i<3; i++){
		for(int j=0; j<3;j++){
			mat[i][j] = 0;
		}
	}
	sleep(50);


	for(int i=0; i<3; i++){
		for(int j=0; j<3;j++){
			char_mat[i][j] = NULL;
		}
	}
	sleep(50);

	gmbFirst = gmbPlaysFirst();
	if(gmbFirst){
		playBallAt(1,1);
	}
	eraseDisplay();
	while (restartGame == false){
		//eraseDisplay();
		displayBoard();
		displayCenteredTextLine(12," Your Turn!   ");
		displayCenteredTextLine(14,"Press Middle Button to End.");
		//Enter button for opponent play
		if (getButtonPress(buttonEnter)){
			eraseDisplay();
			displayBoard();
			//scan for red circle and put it into array
			updateOpponentPlay();
			//show where opponent went
			displayBoard();
			//update turn counter
			foePlayCount = foePlayCount + 1;
			//Opponent has played, my turn
			playedTurn = false;
			//look for spot to place my x
			updateMatCheck();
			int count = 0;
			for(int i=0;i<3;i++){
				for(int j=0;j<3;j++){
					if(mat[i][j]!=0){
						count++;
						}
					}
			}
				if (count == 9){
				displayCenteredTextLine(2," It's a DRAW !! ");
				}
			 // If none of the cells are empty
				else if (restartGame == false){
					nextPlay();//PLAY GAME.. Keep a boolean that lets the program run only when its true
					extraWinCheck();
				}


		}
	}
}

//--------------------------------------------------------------------
//												 FUNCTIONS

	//Reset matCheck
void resetMatCheck(){
	for (int i = 0; i<3; i++){
		for (int j = 0; j<3;j++){
			matCheck[i][j] = false;
		}
	}
	sleep(50);
}
//------------------------------------------------------------------
// SCANS FOR A RED DOT
//------------------------------------------------------------------
void updateOpponentPlay(){
	/*if(mat[atX][atY] == emptyBox){// && !(matCheck[atX][atY])){//
		*/
		bool stopScanning = false;
while (stopScanning == false){
	for (float j = 2; j >= 0; j-=1)
	{
		for (float i = 2; i >= 0;i-=1)
		{
			Goto(i+0.5,j+0.5, true);
			if (scanForRed() == true && mat[i][j] != foe){
				mat[i][j] = foe;
				char_mat[i][j]='o';
				matCheck[i][j] = true;
				foundOppPlay = true;
				//trigger breaks in the for loops containing this
				stopScanning = true;
			}
			//break the for loop
			if (stopScanning == true)
				break;
		}
		//break the for loop
		if (stopScanning == true)
				break;
	}
	goHome();
	playTone(30,100);
	sleep(3000);
}
	displayCenteredTextLine(10,"You played at (%d,%d)",atX,atY);
}

void playBallAt(int x, int y){

	displayCenteredTextLine(5,"going  to  play  at  (%d,%d)",x,y);
	drawXat(x, y);

	//because of errors dont use mat[atX][atY]
	mat[x][y] = robot;
	char_mat[x][y]='x';
	playedTurn = true;
	eraseDisplay();
	displayBoard();
}

void diagPlay(int oneTwo){
	if(oneTwo == 1){
		if(mat[0][2] == emptyBox && !(playedTurn)){playBallAt(0,2);}
		else if(mat[1][1] == emptyBox && !(playedTurn)){playBallAt(1,1);}
		else if(mat[2][0]== emptyBox && !(playedTurn)){playBallAt(2,0);}
	}
	else if(oneTwo == 2){
		if(mat[0][0] == emptyBox){playBallAt(0,0);}
		else if(mat[1][1] == emptyBox){playBallAt(1,1);}
		else if(mat[2][2]== emptyBox){playBallAt(2,2);}
	}
}

void horzPlay(int row){
	for (int i = 0; i<3; i++){
		if(mat[i][row] == 0 && !(playedTurn)){
			playBallAt(i,row);
		}
	}
}

void vertPlay(int col){
	for (int i = 0; i<3; i++){
		if(mat[col][i] == 0 && !(playedTurn)){
			playBallAt(col,i);
		}
	}
}

int getDiag(int oneTwo){
	int result = 0;
	if(oneTwo == 1){
		result = (int)char_mat[0][2] + (int)char_mat[1][1] + (int)char_mat[2][0];
	}
	else{
		result = (int)char_mat[0][0] + (int)char_mat[1][1] + (int)char_mat[2][2];
	}

	return result;
}

int getVert(int col){
	int result = 0;
	for (int i = 0; i<3; i++){
		result = result + (int)char_mat[col][i];
	}
	return result;
}

int getHorz(int row){
	int result = 0;
	for (int i = 0; i<3; i++){
		result = result + (int)char_mat[i][row];
	}
	return result;
}


void updateMatCheck(){
	//Reset matCheck
	resetMatCheck();

	//look for where to play
	for (int i = 0; i<3; i++){
		for (int j = 0; j<3;j++){
			if(!(matCheck[i][j]) && mat[i][j]==emptyBox && !(foundOppPlay)){
			//if It has not check this spot on the mat and
			//	 There is no ball on that spot of the map and
			//	 It still hasn't found the opponent's play
				//Goto(i,j);
				//a break statement could make a tiny difference here
			}
		}
	}

	//Reset foundPlay
	foundOppPlay = false;
}

void extraWinCheck(){
	updateMatCheck();
	//displayCenteredTextLine(7,"Performing nextPlay at")
	int d1 = getDiag(1); int d2 = getDiag(2);
	int v0 = getVert(0);int v1 = getVert(1);int v2 = getVert(2);
	int h0 = getHorz(0);int h1 = getHorz(1);int h2 = getHorz(2);

	if(mat[1][1]==emptyBox && foePlayCount==1 &&!(playedTurn)){
		//playBallAt(1,1);
	}
	else{

		if(v0==360 || v1==360 || v2 == 360 || h0==360 || h1==360 || h2 == 360|| d1 == 360||d2==360){
			eraseDisplay();
			displayCenteredBigTextLine(3,"I WIN");
			displayCenteredBigTextLine(5,"New game in 5 seconds.");
			restartGame = true;
		}
		else if(v0==333 || v1==333 || v2 == 333 || h0==333 || h1==333 || h2 == 333|| d1 == 333||d2==333){
			eraseDisplay();
			displayCenteredBigTextLine(3,"YOU WIN");
			displayCenteredBigTextLine(5,"New game in 5 seconds.");
			restartGame = true;
		}
	}
}

void nextPlay(){
	//displayCenteredTextLine(7,"Performing nextPlay at")
	int d1 = getDiag(1); int d2 = getDiag(2);
	int v0 = getVert(0);int v1 = getVert(1);int v2 = getVert(2);
	int h0 = getHorz(0);int h1 = getHorz(1);int h2 = getHorz(2);

	if(mat[1][1]==emptyBox && foePlayCount==1 &&!(playedTurn)){
		playBallAt(1,1);
	}
	else{

		if(v0==360 || v1==360 || v2 == 360 || h0==360 || h1==360 || h2 == 360|| d1 == 360||d2==360){
			eraseDisplay();
			displayCenteredBigTextLine(3,"I WIN");
			displayCenteredBigTextLine(5,"New game in 5 seconds.");
			restartGame = true;
		}
		else if(v0==333 || v1==333 || v2 == 333 || h0==333 || h1==333 || h2 == 333|| d1 == 333||d2==333){
			eraseDisplay();
			displayCenteredBigTextLine(3,"YOU WIN");
			displayCenteredBigTextLine(5,"New game in 5 seconds.");
			restartGame = true;
		}

		//1---1)CHECK WINS opportunities first
		if(v0==14){vertPlay(0);}
		else if(v1==240 ){vertPlay(1);}
		else if(v2==240 ){vertPlay(2);}

		//horizontals
		else if (h0==240){horzPlay(0);}
		else if (h1==240 ){horzPlay(1);}
		else if (h2==240){horzPlay(2);}

		//diagonals
		else if(d1==240){diagPlay(1);}
		else if(d2==240){diagPlay(2);}

		//2---2)Then BLOCKING OPPONENT
		//DIRECT BLOCKING
		//diagonals
		else if(d1==222){diagPlay(1);}
		else if(d2==222){diagPlay(2);}

		//vertical
		else if(v0==222){vertPlay(0);}
		else if(v1==222){vertPlay(1);}
		else if(v2==222){vertPlay(2);}

		//horizontals
		else if (h0==222){horzPlay(0);}
		else if (h1==222){horzPlay(1);}
		else if (h2==222){horzPlay(2);}


		//INDIRECT BLOCKING:

		//diagonals
		else if((d1%foe) == 0){diagPlay(1);}
		else if((d2%foe)==0){diagPlay(2);}

		//verticals
		else if((v0%foe)==0){vertPlay(0);}
		else if((v1%foe)==0){vertPlay(1);}
		else if((v2%foe)==0){vertPlay(2);}

		//horizontals
		else if ((h0%foe) == 0){horzPlay(0);}
		else if ((h1%foe) == 0){horzPlay(1);}
		else if ((h2%foe) == 0){horzPlay(2);}

		//play anywhere
		else{
			for (int i = 0; i<3; i++){
				for(int j = 0; j<3; j++){
					if(mat[i][j] == emptyBox && !(playedTurn)){
						playBallAt(i,j);
						break;
					}
				}
			}
			sleep(50);
		}

		sleep(50);
	}
}

bool gmbPlaysFirst(){
	bool result = false;
	while (true){
		eraseDisplay();
		displayCenteredTextLine(4,"        RButton = You First------->");
		displayCenteredTextLine(5,"<-------LButton = Me First");

		if (getButtonPress(buttonRight)){
			displayCenteredTextLine(3,"PLAY!!!!");
			result = false;
			break;
		}
		else if (getButtonPress(buttonLeft)){
			displayCenteredTextLine(3,"I PLAY!!!!");
			result = true;
			break;
		}
	}

	return result;

}





	/*---------------------------------------------------------------------------------------
	Enter Code to move arm, call for any required function when required
	---------------------------------------------------------------------------------------*/



/*---------------------------------------------------------------------------------------
// CODE TO DRW X
---------------------------------------------------------------------------------------*/
